[project]
name = "bepi-region-prediction-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bepi-region-prediction",
    "hermpy>=0.2.7",
    "netcdf4>=1.7.4",
    "planetary-coverage>=1.2.1",
    "plotly>=6.9.0",
    "scipy>=1.18.0",
    "spiceypy>=8.2.0",
    "streamlit[charts]>=1.60.0",
    "xarray>=2026.7.0",
]

[tool.uv.workspace]
members = [
    "bepi-region-prediction",
]

[tool.uv.sources]
bepi-region-prediction = { workspace = true, editable = true }
